language: node_js
sudo: false
node_js:
  - "node"
  - "lts/*"
  - "8"
  - "6"
env:
  - KARMA_VERSION=1.0
  - KARMA_VERSION=1.1
  - KARMA_VERSION=1.2
  - KARMA_VERSION=1.3
  - KARMA_VERSION=1.4
  - KARMA_VERSION=1.5
  - KARMA_VERSION=1.6
  - KARMA_VERSION=1.7
addons:
  chrome: stable
before_install:
  - npm install --save-dev karma@"$KARMA_VERSION"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CHROME_BIN=chromium-browser
